### DISCUSSION TITLE
Seeking advice on my very hacky "schema guessing" to generate YAML Paths with wildcards matching non-str document nodes

### DISCUSSION THREAD

**Discussion by AndydeCleyre** [wwkimball/yamlpath#200] [Q&A]
Hello!

It might be best if I lead with the example, then explain.

My yamlpath-powered tool, [NestedTextTo](https://github.com/andydecleyre/nestedtextto), in the `feature/experimental-schema-guessing` branch, behaves as follows:

`sample.toml`:

```toml
title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"
```

```console
$ toml2nt sample.toml --to-schema
```

```yaml
date:
  - owner.dob
boolean:
  - database.enabled
number:
  - database.ports[0]
  - database.ports[1]
  - database.ports[2]
  - database.data[1][0]
  - database.temp_targets.cpu
  - database.temp_targets.case

# Above is a schema that literally matches the current data.
# Below, for your review, is a guess at a better schema.

# date:
#   - owner.dob
# boolean:
#   - database.enabled
# number:
#   - database.temp_targets.case
#   - database.ports.*
#   - database.temp_targets.cpu
#   - database.data.1.*
```

The part I'm working on is that commented bit in the output. In this case, it is producing the result I want: an efficient list of properly matching YAML Paths for each non-string node.

This example has TOML input, but it works the same for YAML input.

But the way I construct these guesses is fragile; I'm deconstructing YAMLPath segments, doing string manipulations, then reconstructing, and it'll probably break hard on YAML Paths that include special characters, etc. And I'm just guessing that if the first array item is a match, it's ok to wildcard that index... but I'm ok with that heuristic for now.

So I'd very much appreciate any ideas about how to do this better, more robustly handling weird paths, using yamlpath's own objects and functions in more places rather than hoping that joining strings will just be fine.

The function which does this is `nt2.yamlpath_tools.guess_briefer_schema`, copied at the bottom of this post. It takes a `dict` parameter with more literal matches; in this case:

```python
{
    'boolean': ['database.enabled'],
    'date': ['owner.dob'],
    'number': [
        'database.ports[0]',
        'database.ports[1]',
        'database.ports[2]',
        'database.data[1][0]',
        'database.temp_targets.cpu',
        'database.temp_targets.case'
    ]
}
```
and returns, in this case:
```python
{
    'boolean': ['database.enabled'],
    'date': ['owner.dob'],
    'number': [
        'database.ports.*',
        'database.temp_targets.cpu',
        'database.data.1.*',
        'database.temp_targets.case'
    ]
}
```

And now, hidden behind this fold to protect the faint of heart, is the function itself, in its current state:

<details>
  <summary>Here be dragons</summary>

```python
def guess_briefer_schema(schema: dict[str, list[str]]) -> dict[str, list[str]]:
    """
    Suggest an alternative schema, with low confidence.

    Args:
        schema: A map of type names ('date', 'boolean', 'number', 'null') to lists of YAML Paths.

    Returns:
        A dumb guess at an alternative schema that matches more patterns and fewer literal paths.
    """
    # This probably breaks on paths with YAMLPath separators/tokens as part of the values/keys
    briefer_schema = {}

    for vartype, ypaths in schema.items():
        pattern_paths = set()

        # Collect, replacing [0] indexes with * wildcards:
        for ypath in map(YAMLPath, ypaths):
            segments = ['*' if seg[-1] == 0 else str(seg[-1]) for seg in ypath.unescaped]
            sep = str(ypath.seperator)  # sic
            entry = f"{sep if sep == '/' else ''}{sep.join(segments)}"
            pattern_paths.add(entry)

        # Prune:
        for entry in list(pattern_paths):
            indices_to_check_for_existing_wildcards = []
            ypath = YAMLPath(entry)
            sep = str(ypath.seperator)  # sic
            removed = False
            for i, segment in enumerate(ypath.unescaped):
                try:
                    int(segment[-1])
                except (ValueError, TypeError):
                    continue
                else:
                    indices_to_check_for_existing_wildcards.append(i)
            for num_of_indices in range(1, len(indices_to_check_for_existing_wildcards) + 1):
                if removed:
                    break
                for wildcard_indices in combinations(
                    indices_to_check_for_existing_wildcards, num_of_indices
                ):
                    segments = [str(seg[-1]) for seg in ypath.unescaped]
                    for i in wildcard_indices:
                        segments[i] = '*'
                    if f"{sep if sep == '/' else ''}{sep.join(segments)}" in pattern_paths:
                        pattern_paths.remove(entry)
                        removed = True
                        break

        briefer_schema[vartype] = list(pattern_paths)
    return briefer_schema
```

</details>
