### ISSUE TITLE
Unable to change scalar nodes from null to anything else

### ISSUE THREAD

**Issue by wwkimball** [wwkimball/yamlpath#110]
Note to self:  Users are able to create null values but once a node is null, that value cannot be changed to anything else.  Example:

```yaml
---
scalar_string: value
scalar_null:
scalar_int: 1028
scalar_bool: true
```

## Actual Result
```shell
$ cat scalars.yaml | yaml-set --change=/scalar_null --value=new
---
scalar_string: value
scalar_null:
scalar_int: 1028
scalar_bool: true
```

## Expected Result
```shell
$ cat scalars.yaml | yaml-set --change=/scalar_null --value=new
---
scalar_string: value
scalar_null: new
scalar_int: 1028
scalar_bool: true
```
