### ISSUE TITLE
Question on merge array types

### ISSUE THREAD

**Issue by josephlim75** [wwkimball/yamlpath#159]
I have 2 yaml files with the following typed array

file1.yaml
```yaml
external:
  - name: DBSERVER
    value: FILE1VALUE
  - name: DBURL
    value: FILE1VALUE
  - name: FILE1
    value: FILE1VAL
```

file2.yaml
```yaml
external:
  - name: DBSERVER
    value: FILE2VALUE
  - name: DBURL
    value: FILE2VALUE
  - name: FILE2
    value: FILE2VALUE
```

## Expected Results
```yaml
external:
  - name: DBSERVER
    value: FILE2VALUE
  - name: DBURL
    value: FILE2VALUE
  - name: FILE2
    value: FILE2VALUE
  - name: FILE1
    value: FILE1VALUE
```

How do I configure the rules so that both file can merge.  If I'm using a simple array with `unique` merge option, that works well.  When I use complex type array, it is not giving the expected result.

Works for simple array like

```
external:
  - one
  - two
```

```
external:
  - three
  - one
  - four
 ```

result
```
external:
  - one
  - two
  - three
  - four
```
