### ISSUE TITLE
Deleting keys deleted post-comment instead of pre-comment

### ISSUE THREAD

**Issue by wwkimball** [wwkimball/yamlpath#170]
## Operating System

1. Name/Distribution:  ANY
2. Version:  ANY

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions):  ANY
2. Python Version:  ANY Supported
3. Version of yamlpath installed:  3.6.4
4. Version of ruamel.yaml installed:  ANY Supported

## Minimum sample of YAML (or compatible) data necessary to trigger the issue

```yaml
---
# test.yaml
key1: value1

# Pre-comment
remove_this: key

# Post-comment
keep_this: other key
```

## Complete steps to reproduce the issue when triggered via:

1. yaml-set --delete --change=/remove_this test.yaml

## Expected Outcome

```yaml
---
# test.yaml
key1: value1

# Post-comment
keep_this: other key
```

## Actual Outcome

```yaml
---
# test.yaml
key1: value1

# Pre-comment
keep_this: other key
```

As you can see, the Pre-comment was preserved while both the post-comment and all whitespace after the target key was deleted.
