### ISSUE TITLE
Unexpected results of search

### ISSUE THREAD

**Issue by gdubicki** [wwkimball/yamlpath#206]
## Operating System

1. Name/Distribution: macOS 
2. Version: Monterey 12.6.1 (21G217)

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions): CPython from homebrew
2. Python Version: 3.11.0
3. Version of yamlpath installed: 3.6.9
4. Version of ruamel.yaml installed: 0.17.21

## Minimum sample of YAML (or compatible) data necessary to trigger the issue

```yaml
projects_and_groups:

  "*":
    merge_requests_approval_rules:
      standard:
        approvals_required: 1
        name: "All eligible users"

  "foo/bar":
    merge_requests_approval_rules:
      dev-uat:
        groups:
          - some_group
        users:
          - a_user
```

## Complete steps to reproduce the issue when triggered via:

YAML Path: `"**.merge_requests_approval_rules.*[.=users]"`

## Expected Outcome

1 result, the array at "projects_and_groups."foo/bar".merge_requests_approval_rules.dev-uat.users".

## Actual Outcome

Exception: `Cannot add PathSegmentTypes.MATCH_ALL subreference to dictionaries at 'None' in '**.merge_requests_approval_rules.*[.=users]'.`

**Comment by gdubicki** [comment]
The code in question is in this PR https://github.com/gitlabform/gitlabform/pull/467/files?diff=split&w=1, in the `gitlabform/configuration/transform.py` file, the `UserTransformer` class, `_do_transform` method.

The test that shows how it fails is in the same PR, in the `tests/unit/configuration/transform/test_user_and_group_transformers.py` file.

<br/>

What I find strange here is that without the `"*":` dict key:

```yaml
projects_and_groups:

  # "*":
  #   merge_requests_approval_rules:
  #     standard:
  #       approvals_required: 1
  #       name: "All eligible users"

  "foo/bar":
    merge_requests_approval_rules:
      dev-uat:
        groups:
          - some_group
        users:
          - a_user
```
...my code works like expected - I am getting a single, correct result.

<br/>

What is even more strange to me is that if I comment out _part_ of the `"*":` dict key like this:

```yaml
projects_and_groups:

  "*":
    merge_requests_approval_rules:
      # standard:
      #   approvals_required: 1
      #   name: "All eligible users"

  "foo/bar":
    merge_requests_approval_rules:
      dev-uat:
        groups:
          - some_group
        users:
          - a_user
```
...I am getting 2 results, but one of them is `None`. I hope that this screenshot from IntelliJ provides enough data about this case:
<img width="1438" alt="Screenshot 2023-01-01 at 11 59 48" src="https://user-images.githubusercontent.com/566632/210168363-ea8155a5-077a-44ce-8482-d305b2b24f06.png">
