### ISSUE TITLE
Is it possible to assign non-primitive values to nodes?

### ISSUE THREAD

**Issue by abramov-oleg** [wwkimball/yamlpath#219]
## Operating System

Ubuntu 20.04.6 LTS

## Version of Python and packages in use at the time of the issue.

Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) 
[GCC 11.4.0] on linux

Version of yamlpath installed: 3.8.0
Version of ruamel.yaml installed: 0.17.21

## Complete steps to reproduce the issue when triggered via Library:

```python

import sys
from types import SimpleNamespace

from yamlpath.common import Parsers
from yamlpath.wrappers import ConsolePrinter
from yamlpath import Processor
from yamlpath import YAMLPath


logging_args = SimpleNamespace(quiet=False, verbose=False, debug=False)
log = ConsolePrinter(logging_args)

yaml_editor = Parsers.get_yaml_editor()

yaml_str_base = """\
sports:
  football:
    - Dallas Cowboys
    - Miami Dolphins
  basketball:
"""
base_data, _ = Parsers.get_yaml_data(yaml_editor, log, yaml_str_base, literal=True)

yaml_str_mod = """\
add_basketball:
  path: sports.basketball
  value:
    - Boston Celtics
    - Detroit Pistons
"""
mod_data, _ = Parsers.get_yaml_data(yaml_editor, log, yaml_str_mod, literal=True)

processor = Processor(log, base_data)

for rule_name, rule in mod_data.items():
    processor.set_value(YAMLPath(rule['path']), rule['value'], mustexist=True)

yaml_editor.dump(base_data, sys.stdout)

```

## Expected Outcome

```
---
sports:
  football:
    - Dallas Cowboys
    - Miami Dolphins
  basketball:
    - Boston Celtics
    - Detroit Pistons
```

## Actual Outcome

```
---
sports:
  football:
    - Dallas Cowboys
    - Miami Dolphins
  basketball: "['Boston Celtics', 'Detroit Pistons']"
```

Similarly for dict nodes, `set_value()` seems to convert them to strings.

Am I doing something wrong or this use case is not supported?
