### ISSUE TITLE
Identical non-String values cannot be independently changed

### ISSUE THREAD

**Issue by raz3k** [wwkimball/yamlpath#44]
## Operating System

1. Name/Distribution: CentOS
2. Version: pre-7.7

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions): Python 3.6 from EPEL
2. Python Version: Python 3.6.8
3. Version of yamlpath installed: 2.3.0
4. Version of ruamel.yaml installed: 0.16.5

## Minimum sample of YAML (or compatible) data necessary to trigger the issue
```
---
somestring:
  string:
    someotherstring: true

otherstring:
  default:
    config:
      deploy:
        me: true
```
## Complete steps to reproduce the issue when triggered via:
```
from yamlpath.exceptions import YAMLPathException
from yamlpath.func import get_yaml_data, get_yaml_editor
from yamlpath import Processor
from yamlpath.wrappers import ConsolePrinter
from ruamel.yaml import YAML

class Args:
  debug = False
  verbose = False
  quiet = True

instance = YAML()

instance.default_flow_style = False
instance.explicit_start = True

yaml = get_yaml_editor()

log = ConsolePrinter(Args())
yaml_data = get_yaml_data(yaml, log, "/tmp/input.yaml")

processor = Processor(log, yaml_data)
try:
    processor.set_value("otherstring.default.config.deploy.me", "set_value")
except YAMLPathException as ex:
    log.critical(ex, 119)

with open("/tmp/output.yaml", 'w') as yaml_dump:
       instance.dump(yaml_data, yaml_dump)
```
## Expected Outcome
```
---
somestring:
  string:
    someotherstring: true

otherstring:
  default:
    config:
      deploy:
        me: set_value
```
## Actual Outcome
```
---
somestring:
  string:
    someotherstring: set_value

otherstring:
  default:
    config:
      deploy:
        me: set_value
```
